/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module top (
  input I0,
  input I2,
  input I1,
  output Q0,
  output Q3,
  output Q1,
  output Q2,
  output Q4,
  output Q5
);
  wire Q2_temp;
  assign Q3 = (I2 & ~ I1);
  assign Q2_temp = ~ I0;
  assign Q0 = I0;
  assign Q1 = Q2_temp;
  assign Q2 = Q2_temp;
  assign Q4 = I2;
  assign Q5 = I1;
endmodule
